# Generated by Django 5.1.4 on 2025-01-29 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0004_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hrprofile',
            name='address',
        ),
    ]
