# Generated by Django 5.1.4 on 2025-01-29 06:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('employeeapp', '0005_remove_hrprofile_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='hrprofile',
            name='address',
            field=models.TextField(default='address'),
        ),
    ]
